server:
  thread:
    core-pool-size: 100
    maxumum-pool-size: 200
    max-queue-size: 10000
  network:
    tcp-local-address: :8088
    ssl-local-address: :-1
    ziped: true
    max-connect: 1000
    login-time-out: 10000
    router-enable: false
    reuse-address: true
    router:
      config-file: classpath:router-sdk-config.xml
    executor:
      core-pool-size: 16
      maximum-pool-size: 16
    keepalive:
      request-interval: 20
      request-time-out: 40
      forward-event: false
    mina:
      logger:
        exception-caught-log-level: INFO
        message-sent-log-level: NONE
        message-received-log-level: NONE
        session-closed-log-level: NONE
        session-created-log-level: NONE
        session-idle-log-level: NONE
        session-opened-log-level: NONE
    ssl:
      key-store-password: 875925
      key-manager-factory-key-store-password: 875925
      jks-file: classpath:server.jks
  port: 8071

spring:
  datasource:
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      initial-size: 8
      min-idle: 8
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: false
      url: jdbc:oracle:thin:@172.16.3.242:1521:develop
      username: ycb
      password: ycb888888

  redis:
    cluster:
      nodes: 172.16.3.244:6379,172.16.3.244:6380,172.16.3.244:6381,172.16.3.242:6379,172.16.3.242:6380,172.16.3.242:6381
    jedis:
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0
    timeout: 3600000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis-plus:
  mapper-locations: classpath:com/chebei/user/mapper/*Mapper.xml
  type-aliases-package: com.chebei.user.model
  mapper-scanner-base-package: com.chebei.user.mapper
  mapper-scanner-enable: true
  config-location: classpath:mybatis-config.xml
# 下面这个加上可以使map返回空值
#  configuration:
#    call-setters-on-nulls: true

ams:
  processor:
    ext:
      func-refresh-cache: true
      ibatis-processor-class: com.chebei.ams.processor.ext.processor.BatisEventProcessor
      bean-method-processor-class: com.chebei.ams.processor.ext.processor.RestfulEventProcessor
      func-conf-mapper-locations: classpath*:/functions/functions-*.xml
      restful-handler-locations: com.chebei.*.service

application:
  host-name: service-dev
  func:
    task-on: false



