# redis集群
spring.redis.cluster.nodes=172.16.3.244:6379,172.16.3.244:6380,172.16.3.244:6381,172.16.3.242:6379,172.16.3.242:6380,172.16.3.242:6381
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-active=200
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1
# 连接池中的最大空闲连接
spring.redis.jedis.pool.max-idle=200
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=0
# 连接超时时间
spring.redis.timeout=3600

# 部署所在主机名
application.host-name=service-a


