package com.chebei.user.domain;

public class TsysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.USER_CODE
     *
     * @mbg.generated
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.LOGIN_PWD
     *
     * @mbg.generated
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.ORG_ID
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.LOCK_STATUS
     *
     * @mbg.generated
     */
    private String lockStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.USER_STATUS
     *
     * @mbg.generated
     */
    private String userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.EXT_FLAG
     *
     * @mbg.generated
     */
    private String extFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.MOBILE_TEL
     *
     * @mbg.generated
     */
    private String mobileTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.GMT_MODIFY
     *
     * @mbg.generated
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.GMT_PASS
     *
     * @mbg.generated
     */
    private Long gmtPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.USER_TYPE
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.GMT_CREATE
     *
     * @mbg.generated
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.EXT_FIELD_1
     *
     * @mbg.generated
     */
    private String extField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSYS_USER.EXT_FIELD_2
     *
     * @mbg.generated
     */
    private String extField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.USER_CODE
     *
     * @return the value of TSYS_USER.USER_CODE
     *
     * @mbg.generated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.USER_CODE
     *
     * @param userCode the value for TSYS_USER.USER_CODE
     *
     * @mbg.generated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.USER_NAME
     *
     * @return the value of TSYS_USER.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.USER_NAME
     *
     * @param userName the value for TSYS_USER.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.LOGIN_PWD
     *
     * @return the value of TSYS_USER.LOGIN_PWD
     *
     * @mbg.generated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.LOGIN_PWD
     *
     * @param loginPwd the value for TSYS_USER.LOGIN_PWD
     *
     * @mbg.generated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.ORG_ID
     *
     * @return the value of TSYS_USER.ORG_ID
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.ORG_ID
     *
     * @param orgId the value for TSYS_USER.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.EMAIL
     *
     * @return the value of TSYS_USER.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.EMAIL
     *
     * @param email the value for TSYS_USER.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.LOCK_STATUS
     *
     * @return the value of TSYS_USER.LOCK_STATUS
     *
     * @mbg.generated
     */
    public String getLockStatus() {
        return lockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.LOCK_STATUS
     *
     * @param lockStatus the value for TSYS_USER.LOCK_STATUS
     *
     * @mbg.generated
     */
    public void setLockStatus(String lockStatus) {
        this.lockStatus = lockStatus == null ? null : lockStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.USER_STATUS
     *
     * @return the value of TSYS_USER.USER_STATUS
     *
     * @mbg.generated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.USER_STATUS
     *
     * @param userStatus the value for TSYS_USER.USER_STATUS
     *
     * @mbg.generated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.EXT_FLAG
     *
     * @return the value of TSYS_USER.EXT_FLAG
     *
     * @mbg.generated
     */
    public String getExtFlag() {
        return extFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.EXT_FLAG
     *
     * @param extFlag the value for TSYS_USER.EXT_FLAG
     *
     * @mbg.generated
     */
    public void setExtFlag(String extFlag) {
        this.extFlag = extFlag == null ? null : extFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.MOBILE_TEL
     *
     * @return the value of TSYS_USER.MOBILE_TEL
     *
     * @mbg.generated
     */
    public String getMobileTel() {
        return mobileTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.MOBILE_TEL
     *
     * @param mobileTel the value for TSYS_USER.MOBILE_TEL
     *
     * @mbg.generated
     */
    public void setMobileTel(String mobileTel) {
        this.mobileTel = mobileTel == null ? null : mobileTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.GMT_MODIFY
     *
     * @return the value of TSYS_USER.GMT_MODIFY
     *
     * @mbg.generated
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.GMT_MODIFY
     *
     * @param gmtModify the value for TSYS_USER.GMT_MODIFY
     *
     * @mbg.generated
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.GMT_PASS
     *
     * @return the value of TSYS_USER.GMT_PASS
     *
     * @mbg.generated
     */
    public Long getGmtPass() {
        return gmtPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.GMT_PASS
     *
     * @param gmtPass the value for TSYS_USER.GMT_PASS
     *
     * @mbg.generated
     */
    public void setGmtPass(Long gmtPass) {
        this.gmtPass = gmtPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.USER_TYPE
     *
     * @return the value of TSYS_USER.USER_TYPE
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.USER_TYPE
     *
     * @param userType the value for TSYS_USER.USER_TYPE
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.GMT_CREATE
     *
     * @return the value of TSYS_USER.GMT_CREATE
     *
     * @mbg.generated
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.GMT_CREATE
     *
     * @param gmtCreate the value for TSYS_USER.GMT_CREATE
     *
     * @mbg.generated
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.REMARK
     *
     * @return the value of TSYS_USER.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.REMARK
     *
     * @param remark the value for TSYS_USER.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.EXT_FIELD_1
     *
     * @return the value of TSYS_USER.EXT_FIELD_1
     *
     * @mbg.generated
     */
    public String getExtField1() {
        return extField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.EXT_FIELD_1
     *
     * @param extField1 the value for TSYS_USER.EXT_FIELD_1
     *
     * @mbg.generated
     */
    public void setExtField1(String extField1) {
        this.extField1 = extField1 == null ? null : extField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSYS_USER.EXT_FIELD_2
     *
     * @return the value of TSYS_USER.EXT_FIELD_2
     *
     * @mbg.generated
     */
    public String getExtField2() {
        return extField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSYS_USER.EXT_FIELD_2
     *
     * @param extField2 the value for TSYS_USER.EXT_FIELD_2
     *
     * @mbg.generated
     */
    public void setExtField2(String extField2) {
        this.extField2 = extField2 == null ? null : extField2.trim();
    }
}