package com.chebei.user.mapper;

import com.chebei.user.domain.TsysUser;
import com.chebei.user.domain.TsysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    long countByExample(TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    int deleteByExample(TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    int insert(TsysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    int insertSelective(TsysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    List<TsysUser> selectByExample(TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    TsysUser selectByPrimaryKey(String userCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TsysUser record, @Param("example") TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TsysUser record, @Param("example") TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSYS_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsysUser record);
}